generate_ANOVA_input_columns

M = [PPT_NUM INPUT_METHOD TECHNIQUE TARGET TRIAL ...
    TIME_ON_TASK ...
    EMDAT_values_all.abspathanglesrate ...
    EMDAT_values_all.eyemovementvelocity ...
    EMDAT_values_all.fixationrate ...
    EMDAT_values_all.length ...
    EMDAT_values_all.meanabspathangles ...
    EMDAT_values_all.meanfixationduration ...
    EMDAT_values_all.meanpathdistance ...
    EMDAT_values_all.meanrelpathangles ...
    EMDAT_values_all.numfixations ... 
    EMDAT_values_all.numsamples ...
    EMDAT_values_all.numsegments ...
    EMDAT_values_all.relpathanglesrate ...
    EMDAT_values_all.stddevabspathangles ...
    EMDAT_values_all.stddevfixationduration ...
    EMDAT_values_all.stddevpathdistance ...
    EMDAT_values_all.stddevrelpathangles ...
    EMDAT_values_all.sumabspathangles ...
    EMDAT_values_all.sumfixationduration ...
    EMDAT_values_all.sumpathdistance ...
    EMDAT_values_all.sumrelpathangles];

missing = find(M(:, 3) == 4);

M(missing, :) = [];

csvwrite('222_ANOVA_input.csv', M)

clear missing